### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by Cupcakes123** [Fukki/auto-shit#4]
[mods] ERROR: Please contact the module's author: https://github.com/Fukki/auto-shit/issues/
Error: [dispatch] [auto shit] hook: unmapped packet "S_INVEN"
    at Dispatch.createHook (C:\Users\x\Desktop\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\x\Desktop\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (C:\Users\x\Desktop\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at new autoShit (C:\Users\x\Desktop\CaaliTeraProxy\mods\auto-shit-master\index.js:157:6)
    at ModuleManager.load (C:\Users\x\Desktop\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:156:35)
    at C:\Users\x\Desktop\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\x\Desktop\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:119:31)
    at Socket.<anonymous> (C:\Users\x\Desktop\CaaliTeraProxy\bin\connectionManager.js:54:47)
    at Socket.emit (events.js:208:15)

**Comment by Fukki** [comment]
fixed
