### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by spedoka** [Fukki/auto-shit#6]
[17:47:12.234] [mods] ERROR: Module "Auto Shit" (Auto Shit) could not be loaded!
[17:47:12.235] [mods] ERROR: Please contact the module's author: https://github.com/Fukki/auto-shit/issues/
[17:47:12.235] C:\Users\Spedo\AppData\Local\Programs\TeraToolbox\mods\auto-shit-master\index.js:157
	if (mod.majorPatchVersion => 85) {
	        

SyntaxError: Malformed arrow function parameter list
    at Module._compile (internal/modules/cjs/loader.js:752:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at ModuleManager.load (C:\Users\Spedo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:147:43)
    at C:\Users\Spedo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)

Now that's the mistake:(

**Comment by Fukki** [comment]
hmm, wrong syntax by me :/
